version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.2
    steps:
      - checkout
      - run: npm ci
      - run: CI=false npm run build

workflows:
  build:
    jobs:
      - build
