version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.2
    steps:
      - checkout
      - run: npm install
      - run: CI=true npm run build

workflows:
  build:
    jobs:
      - build